### ISSUE TITLE
Create a checklist for the field testing

### ISSUE THREAD

**Issue by zRafaF** [HefestusTec/bolinho#189]
### Description

List of things that need to be checked when on field testing

### Affected area

- [ ] Front-End
- [ ] Back-End
- [X] Other

### Documentation version

- [ ] Web
- [ ] PDF

### Modification type

- [ ] Addition
- [ ] Removal
- [ ] Update to existing page

### Suggestion

- [ ] Bottom z axis stopper
- [ ] Top z axis stopper
- [ ] (if implemented) almost equal value of the before save optimizer, see #185
- [ ] Z calibration

### Priority

High

**Comment by zRafaF** [comment]
Check measurement units, for example is the load cell in grams or newtons?
